;完全に作成者個人の設定です。参考までにどうぞ。

[Mac DeviceProfile]
+CVars=r.MaxAnisotropy=16
+CVars=r.Metal.OptLevel=2
+CVars=r.Shadow.MaxCSMResolution=1024
+CVars=r.Shadow.PerObjectResolutionMax=1024
+CVars=r.Shadow.PerObjectResolutionMin=512
+CVars=r.AmbientOcclusion.Power=0.6
+CVars=sg.ResolutionQuality=59.259259

[Mac_Low DeviceProfile]
BaseProfileName=Mac_VeryHigh

[Mac_M1 DeviceProfile]
BaseProfileName=Mac_VeryHigh
