;M1Max 32GB以上のスペックならめっちゃ良い感じになります。
;ゲーム内設定で120FPSも設定できるようになります。
;あんまり厳密にテストしてないので効いてないCVarもあるかも
;大体60FPS安定くらいで調節しているので、各種値は良い感じに調節してください。

[Mac DeviceProfile]
+CVars=r.Metal.ShaderCodeLoadMode=2
+CVars=r.Metal.OptLevel=2
+CVars=r.Shadow.PerObjectResolutionMax=1024
+CVars=r.Shadow.PerObjectResolutionMin=512
+CVars=r.AmbientOcclusion.Power=0.6
+CVars=sg.ResolutionQuality=59.259259
+CVars=sg.EffectsQuality=3
+CVars=r.Upscale.Quality=3
+CVars=r.ParallelFrustumCull=1
+CVars=r.PSO.LRUCapacity=8192
+CVars=wp.Runtime.EnableHLODCellMappingOptimization=1
+CVars=r.HZBOcclusion=0
+CVars=r.TemporalAAFilterSize=1.0
+CVars=r.TemporalAASamples=8
+CVars=r.TemporalAACurrentFrameWeight=0.25
+CVars=r.MeshDrawCommands.DynamicInstancing=1
+CVars=r.VT.NumGatherTasks=16
+CVars=s.LevelStreamingComponentsRegistrationGranularity=30
+CVars=r.SSR.Temporal=1
+CVars=r.SSR.HalfResSceneColor=1
+CVars=r.SSS.Quality=1
+CVars=r.SSS.SampleSet=2
+CVars=r.SSS.HalfRes=1
+CVars=r.SSFS.DownSampleFactor=1
+CVars=r.TemporalAA.Algorithm=1

[Mac_High DeviceProfile]
BaseProfileName=Mac_VeryHigh

[Mac_Mid DeviceProfile]
BaseProfileName=Mac_VeryHigh

[Mac_Low DeviceProfile]
BaseProfileName=Mac_VeryHigh

[Mac_M5_High DeviceProfile]
BaseProfileName=Mac_VeryHigh

[Mac_M5 DeviceProfile]
BaseProfileName=Mac_VeryHigh

[Mac_M4_High DeviceProfile]
BaseProfileName=Mac_VeryHigh

[Mac_M4 DeviceProfile]
BaseProfileName=Mac_VeryHigh

[Mac_M3_High DeviceProfile]
BaseProfileName=Mac_VeryHigh

[Mac_M3 DeviceProfile]
BaseProfileName=Mac_VeryHigh

[Mac_M2_High DeviceProfile]
BaseProfileName=Mac_VeryHigh

[Mac_M2 DeviceProfile]
BaseProfileName=Mac_VeryHigh

[Mac_M1_High DeviceProfile]
BaseProfileName=Mac_VeryHigh

[Mac_M1 DeviceProfile]
BaseProfileName=Mac_VeryHigh

