;M1Max 32GB以上のスペックならめっちゃ良い感じになります。
;ゲーム内設定で120FPSも設定できるようになります。
;あんまり厳密にテストしてないので効いてないCVarもあるかも
;大体60FPS安定くらいで調節しているので、各種値は良い感じに調節してください。

[Mac DeviceProfile]
+CVars=sg.ResolutionQuality=50
+CVars=r.AmbientOcclusion.Denoiser=1
+CVars=r.HZBOcclusion=1
+CVars=r.TranslucencyVolumeBlur=1
+CVars=r.Upscale.Quality=3
+CVars=r.Shadow.FilterMethod=1
+CVars=r.Shadow.Denoiser=1
+CVars=r.LightShaftDownSampleFactor=1
+CVars=r.Shadow.RadiusThreshold=0.01
+CVars=r.Shadow.CSM.TransitionScale=2
+CVars=r.Shadow.PerObjectResolutionMax=768
+CVars=r.Shadow.PerObjectResolutionMin=768
+CVars=r.Metal.OptLevel=1
+CVars=r.Metal.ShaderCodeLoadMode=1
+CVars=r.PSO.CacheEvictScheme=1
+CVars=r.PSO.LRUCapacity=2304
+CVars=r.SSR.Quality=3
+CVars=r.SSR.MaxRoughness=1.0
+CVars=r.SSR.HalfResSceneColor=0
+CVars=r.SSR.Temporal=1
+CVars=r.SSS.HalfRes=0
+CVars=r.SSS.Quality=1
+CVars=r.SSS.SampleSet=0
+CVars=r.StaticMeshLODDistanceScale=0.5
+CVars=r.TemporalAA.Algorithm=1
+CVars=r.AntiAliasingMethod=2
+CVars=r.TemporalAACurrentFrameWeight=0.10
+CVars=r.TemporalAAFilterSize=1.0
+CVars=r.TemporalAASamples=8
+CVars=r.MeshBlend.Quality=3
+CVars=r.VRS.Enable=0
+CVars=r.Streaming.UsingKuroStreamingPriority=0
+CVars=r.Kuro.SkeletalMesh.DistanceLODBaseFOV=150.0
+CVars=r.SSFS.DownSampleFator=2
+CVars=a.URO.Enable=0
+CVars=a.URO.EnableScreenRatio=0


[Mac_High DeviceProfile]
BaseProfileName=Mac_VeryHigh

[Mac_Mid DeviceProfile]
BaseProfileName=Mac_VeryHigh

[Mac_Low DeviceProfile]
BaseProfileName=Mac_VeryHigh

[Mac_M5_High DeviceProfile]
BaseProfileName=Mac_VeryHigh

[Mac_M5 DeviceProfile]
BaseProfileName=Mac_VeryHigh

[Mac_M4_High DeviceProfile]
BaseProfileName=Mac_VeryHigh

[Mac_M4 DeviceProfile]
BaseProfileName=Mac_VeryHigh

[Mac_M3_High DeviceProfile]
BaseProfileName=Mac_VeryHigh

[Mac_M3 DeviceProfile]
BaseProfileName=Mac_VeryHigh

[Mac_M2_High DeviceProfile]
BaseProfileName=Mac_VeryHigh

[Mac_M2 DeviceProfile]
BaseProfileName=Mac_VeryHigh

[Mac_M1_High DeviceProfile]
BaseProfileName=Mac_VeryHigh

[Mac_M1 DeviceProfile]
BaseProfileName=Mac_VeryHigh

